name: RunAction

on:
  workflow_dispatch:

jobs:
  TestOs:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - shell: pwsh
        run: |
          pwsh -version
      - uses: bjompen/UpdatePWSHAction@0fa646e86a1535c17d096d547a3ae7521ed7d7ed
      - shell: pwsh
        run: |
          pwsh -version
